image: /home/triton/stingray_docker/catkin_ws/src/stingray_camera/config/alans_room.pgm
resolution: 0.020000
origin: [-12.880000, -12.880000, 0.000000]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196

