map_type:       costmap
obstacle_range: 0.7
raytrace_range: 0.4
#robot_radius: ir_of_robot
robot_radius: 0.15
inflation_radius: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: center_laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
